### ISSUE TITLE
multithread example fails with BorrowMutErr

### ISSUE THREAD

**Issue by estokes** [antoyo/relm#114]
I recently tried to write a gui that uses a background worker thread. It exploded on startup with a BorrowMutErr. The minimal example in relm also has exactly the same problem.

```rust
thread 'main' panicked at 'already borrowed: BorrowMutError', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:809
  10: <core::cell::RefCell<T>>::borrow_mut
             at /checkout/src/libcore/cell.rs:816
  11: relm_core::<impl relm_core::source::SourceFuncs for core::cell::RefCell<relm_core::ChannelData<MSG>>>::prepare
             at /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/relm-core-0.14.4/src/lib.rs:110
  12: relm_core::source::prepare
             at /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/relm-core-0.14.4/src/source.rs:85
  13: g_main_context_prepare
  14: <unknown>
  15: g_main_loop_run
  16: gtk_main
  17: gtk::auto::functions::main
             at /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.4.1/src/auto/functions.rs:273
  18: relm::run
             at /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/relm-0.14.4/src/lib.rs:391
  19: relm::widget::Widget::run
             at /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/relm-0.14.4/src/widget.rs:63
  20: test_relm_multithread::main
             at src/main.rs:99
  21: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  22: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  23: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  24: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  25: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  26: main
  27: __libc_start_main
  28: _start
```

**Comment by estokes** [comment]
Yes it's the published version

**Comment by antoyo** [comment]
I'll release a new version soon, then.

**Comment by estokes** [comment]
Thanks that'd be great

**Comment by antoyo** [comment]
`relm-core` version 0.14.5 was published.
Please tell me if it fixed this isuse.
(By the way, please note that [`syn` does not work on latest nightly](https://github.com/dtolnay/syn/issues/427).).

**Comment by estokes** [comment]
Ok. I already tried with the tip of git, and it did work, kinda, so I think
your release will fix the crash.

However I think you need to call g_main_context_wakeup when a new thing is
sent from a thread. Otherwise the message won't be received until something
wakes up the main thread or the poll timeout expires.

**Comment by antoyo** [comment]
Thanks.
It is fixed in commit de873b244fcb42d08a8cb4cf833a51961a44a689.
I'll deploy a new version soon.
Anything else or can I close this issue?

**Comment by estokes** [comment]
Nope nothing else, thanks!
